#!/usr/bin/env python3
"""Generate unicode_tables.h: run-length encoded category flags for the o200k pretokenizer."""
import sys
import unicodedata

FL_L, FL_N, FL_U, FL_D, FL_WS = 1, 2, 4, 8, 16

# Unicode White_Space property (what regex \s matches), not Python str.isspace().
WHITESPACE = set(
    list(range(0x09, 0x0E)) + [0x20, 0x85, 0xA0, 0x1680]
    + list(range(0x2000, 0x200B)) + [0x2028, 0x2029, 0x202F, 0x205F, 0x3000]
)

def flags(cp: int) -> int:
    cat = unicodedata.category(chr(cp))
    f = 0
    if cat[0] == "L":
        f |= FL_L
    if cat[0] == "N":
        f |= FL_N
    if cat in ("Lu", "Lt", "Lm", "Lo") or cat[0] == "M":
        f |= FL_U
    if cat in ("Ll", "Lm", "Lo") or cat[0] == "M":
        f |= FL_D
    if cp in WHITESPACE:
        f |= FL_WS
    return f

runs = []  # (start_cp, flags)
prev = -1
for cp in range(0x110000):
    f = flags(cp)
    if f != prev:
        runs.append((cp, f))
        prev = f

with open(sys.argv[1] if len(sys.argv) > 1 else "unicode_tables.h", "w") as out:
    out.write("/* generated by gen_unicode.py (Python unicodedata %s) — do not edit */\n"
              % unicodedata.unidata_version)
    out.write("#define UC_NRUNS %d\n" % len(runs))
    out.write("static const uint32_t uc_start[UC_NRUNS] = {")
    out.write(",".join(str(s) for s, _ in runs))
    out.write("};\n")
    out.write("static const uint8_t uc_flag[UC_NRUNS] = {")
    out.write(",".join(str(f) for _, f in runs))
    out.write("};\n")
print(f"{len(runs)} runs")
